- name: Get apt-packages required for installing comet.
  apt: update_cache=yes cache_valid_time=600 name={{item}}
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
  sudo: yes


- name: Create venv dir with correct permissions
  file: path={{ comet_venv }} state=directory mode=0755 owner={{ comet_deploy_user }}
  sudo: yes

- name: Install comet into a virtualenv
  remote_user: "{{ comet_deploy_user }}"
  pip:
    name: "{{ item }}"
    virtualenv: "{{ comet_venv }}"
  with_items:
    cython comet