- name: Get apt-packages required for installing comet.
  apt: update_cache=yes cache_valid_time=600 name={{item}}
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
  become: yes


- name: Create venv dir with correct permissions
  file:
    path: "{{ comet_venv }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
    owner: "{{ comet_deploy_user }}"
  become: yes

- name: Install SSL issues workaround
  pip:
    name: "requests[security]"
    virtualenv: "{{ comet_venv }}"
  become: yes
  become_user: "{{ comet_deploy_user }}"

- name: Install comet into a virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: "{{ comet_venv }}"
  with_items:
    cython comet
  when: not comet_use_fork
  become: yes
  become_user: "{{ comet_deploy_user }}"

- name: Install comet-fork if required
  pip:
    name: "{{ comet_fork_repo }}#egg=comet_fork"
    virtualenv: "{{ comet_venv }}"
  when: comet_use_fork
  become: yes
  become_user: "{{ comet_deploy_user }}"