---
# tasks file for comet

- include: users.yml tags=users
- include: install.yml tags=install

- name: Upload Comet invocation command
  template:
    src: "{{ comet_invoke_template }}"
    dest: "/home/{{ comet_deploy_user }}/{{ comet_invoke_scriptname }}"
    owner: "{{ comet_deploy_user }}"
    group: "{{ comet_user_group }}"
    mode: "u=rwx,g=rx,o=rx"
  become: yes
  #Restart service if invocation has changed:
  notify:
    - restart comet
  tags: config

- name: Upload Comet systemd-service script
  template:
    src: systemd/comet.service.j2
    dest: /etc/systemd/system/comet.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart comet
  tags: config

- name: Start the 'comet' service
  service: name=comet state=started enabled=yes
  become: yes
