- name: Setup comet user-group
  group: name="{{ comet_user_group }}"
  sudo: yes

- name: Create comet deploy/serve users.
  user: name={{item}} group="{{ comet_user_group }}" shell=/bin/bash
  sudo: yes
  with_items: comet_users

- name: Lookup contents of the standard authorized_keys file
  slurp: src=~/.ssh/authorized_keys
  register: authkeys

#    - name: Debug
#      debug: msg="Authkeys \"{{authkeys.content|b64decode}}\""
#      tags: debug

- name: Upload authorized_keys for new users
  authorized_key: user={{item}} key="{{authkeys.content|b64decode}}"
  with_items: comet_users
  sudo: yes