# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "cometvm" do |cometvm| end

  config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
  end

  config.vm.network "forwarded_port", guest: 8098, host: 8198
  config.vm.network "forwarded_port", guest: 8099, host: 8199

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../test/test-comet-role.yml"
      ansible.verbose = "vv"
      ansible.groups = {
      "test" => ["cometvm"],
      "test:vars" => {"ansible_python_interpreter" => "/usr/bin/python3"}
      }

  end

end
