- name: Update base packages
  apt: upgrade=safe update_cache=yes cache_valid_time=600
  sudo: yes

- name: Get pip, wheel, virtualenv
  easy_install: name={{item}}
  sudo: yes
  with_items:
    - pip
    - wheel
    - virtualenv