- name: Update base packages
  apt: upgrade=safe update_cache=yes cache_valid_time=600
  sudo: yes

- name: Get easy_install
  apt: name=python-setuptools,python-dev update_cache=yes cache_valid_time=600
  sudo: yes

- name: Get pip, wheel, virtualenv
  easy_install: name={{item}}
  sudo: yes
  with_items:
    - pip
    - wheel
    - virtualenv

- name: Set timezone to UTC
  shell: timedatectl set-timezone UTC
  when: ansible_date_time.tz != "UTC"
  sudo: yes

- name: Install ntpd
  apt: name=ntp
  sudo: yes