- hosts: voeventnode
  roles:
    - role: swapfile
      sudo: yes
  vars:
    voevent_users:
      - voeventdeploy
      - voeventserve

  tasks:
    - include: tasks/base.yml tags=base
    - include: tasks/users.yml tags=users
    - include: tasks/install.yml tags=install

    - name: Upload Comet invocation command
      copy:
        src: files/invoke-comet.sh
        dest: /home/voeventdeploy/invoke-comet.sh
        owner: voeventdeploy
        group: voevent
        mode: "u=rwx,g=rx,o=rx"
      remote_user: voeventdeploy
      #Restart service if invocation has changed:
      notify:
        - restart voeventnode
      tags: config

    - name: Upload Comet init script
      copy:
        src: files/init/voeventnode.conf
        dest: /etc/init/voeventnode.conf
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      sudo: yes
      #Restart service if init-script has changed:
      notify:
        - restart voeventnode
      tags: config

    - name: Start the 'voeventnode' service
      service: name=voeventnode state=started
      sudo: yes

  handlers:
    - name: restart voeventnode
      service: name=voeventnode state=restarted
      sudo: yes