- hosts: voeventnode
  roles: 
    - role: swapfile
      sudo: yes
  vars:
    voevent_users:
      - voeventdeploy
      - voeventserve

  tasks:
    - include: tasks/base.yml
    - include: tasks/users.yml

    - name: Get apt-packages required for installing comet.
      apt: update_cache=yes cache_valid_time=600 name={{item}}
      with_items:
        - libxml2-dev
        - libxslt1-dev
        - zlib1g-dev
      sudo: yes

    - name: Install required packages into a virtualenv
      pip:
        name: "{{item}}"
        virtualenv: ~/deploy_venv
      remote_user: voeventdeploy
      with_items:
        cython comet

